version: "3"

services:
  bot:
    build: .
    volumes:
      - .:/usr/app/ # for dev only
      - /usr/app/node_modules
    depends_on:
      - redis
      - lavalink
  redis:
    image: redis
  lavalink:
    image: fredboat/lavalink:master
    volumes:
      - "./lavalink-config.yml:/opt/Lavalink/application.yml"
